spring:
  application:
    name: demo

#SpringAI
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY:''}

#OpenAI
openai:
  model: gpt-3.5-turbo
  api:
    key: ${OPEN_AI_API_KEY:''}
    base-url: https://api.openai.com/
    path:
      completions: v1/chat/completions
  max-completions: 1
  temperature: 0

server:
  servlet:
    context-path: /window-assistant-ai

#request
#  curl https://api.openai.com/v1/chat/completions \
#-H "Content-Type: application/json" \
#-H "Authorization: Bearer $OPENAI_API_KEY" \
#  -d '{
#"model": "gpt-3.5-turbo-0125",
#"messages": [
#  {
#    "role": "system",
#    "content": "You are a helpful assistant."
#  },
#  {
#    "role": "user",
#    "content": "Hello!"
#  }
#]
#}'
#

#response
#  {
#    "id": "chatcmpl-123",
#    "object": "chat.completion",
#    "created": 1677652288,
#    "model": "gpt-4o-mini",
#    "system_fingerprint": "fp_44709d6fcb",
#    "choices": [{
#      "index": 0,
#      "message": {
#        "role": "assistant",
#        "content": "\n\nHello there, how may I assist you today?",
#      },
#      "logprobs": null,
#      "finish_reason": "stop"
#    }],
#    "usage": {
#      "prompt_tokens": 9,
#      "completion_tokens": 12,
#      "total_tokens": 21,
#      "completion_tokens_details": {
#        "reasoning_tokens": 0
#      }
#    }
#  }
